version: '2.1'
services:
  pg-0:
    build:
      context: pg-0
    ports:
      - 5432
    environment:
      - BACKUP_SKYNET_URL=https://siasky.net/AABntGRUfXKMG-aP2caot_k-Ud3E9UJAUZdeMuj-0k97iQ
      - BACKUP_PASS=custompassword
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:11
    ports:
      - 5432
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pgpool:
    image: docker.io/bitnami/pgpool:4
    ports:
      - 5432:5432
    depends_on:
      - pg-0
      - pg-1
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - BACKUP_PASS=custompassword
      - PGPOOL_POSTGRES_USERNAME=customuser
      - PGPOOL_POSTGRES_PASSWORD=custompassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: application/backend
    depends_on: 
      - pgpool
    ports:
      - "80:80"
    environment:
      - PYTHONPATH=.
      - BACKUP_PASS=custompassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - DATABASE_URL=postgresql://customuser:custompassword@pgpool:5432/customdatabase

